# -*- mode: ruby -*-
# vi: set ft=ruby :
#^syntax detection


VAGRANTFILE_API_VERSION = "2"
Vagrant.require_version ">= 1.8.1"
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'


$cimaster="172.10.10.10"
$manager1="172.10.10.20"
$worker1="172.10.10.30"
$worker2="172.10.10.40"
$worker3="172.10.10.50"
$registry="#{$cimaster}:5000"




Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "bento/ubuntu-16.04"

  config.vm.provider :virtualbox do |vb|
    vb.memory=1024
    vb.cpus = 1
  end

   config.vm.provision "docker"
   config.vm.provision "shell", privileged:false,path:"scripts/provision/installs.sh", args:["#{$cimaster}","#{$manager1}"]

   config.vm.define "cimaster" do |c|
     c.vm.hostname="cimaster"
     c.vm.network "private_network", ip:$cimaster
    end

   config.vm.define "manager1" do |c|
     c.vm.hostname="manager1"
     c.vm.network "private_network", ip:$manager1
   end

   config.vm.define "worker1" do |c|
     c.vm.hostname="worker1"
     c.vm.network "private_network", ip:$worker1
   end

   config.vm.define "worker2" do |c|
     c.vm.hostname="worker2"
     c.vm.network "private_network", ip:$worker2
   end

   config.vm.define "worker3" do |c|
     c.vm.hostname="worker3"
     c.vm.network "private_network", ip:$worker3
   end

   config.vm.define "worker3" do |c|
     c.vm.hostname="worker3"
     c.vm.network "private_network", ip:$worker3
   end

end
