version: '2'
services:

    cicd:
        extends:
           file: devops/cicd/docker-compose.yml
           service: cicd
        environment:
            - 'APP_NAME=checklist'
            - 'DEPLOY_TO_SERVER=dev'
            - 'DOCKER_USER=andresfuentes'
            - 'DOCKER_PASSWORD=tresm1104'
            - 'DOCKER_TARGET=tcp://adc-swarm-master.eastus.cloudapp.azure.com:4243'
            - 'GIT_URL=https://github.com/andresfuentes/Checklist.git'
            - 'HEALTH_CHECK=http://adc-swarm-master.eastus.cloudapp.azure.com:8080/management/health'

            - 'SERVICE_ENV=dev,swagger'
            - 'SERVICE_PORT=9090'
            - 'SERVICE_ES_CLUSTER=elasticsearch'
            - 'SERVICE_ES_NODE=adc-database.eastus.cloudapp.azure.com:9300'

            - 'SERVICE_DB=jdbc:postgresql://adc-database.eastus.cloudapp.azure.com:5432/Checklist'
            - 'DB_URL=adc-database.eastus.cloudapp.azure.com:5432/Checklist'
            - 'DB_USER=postgres'
            - 'DB_PASSWORD=pwc123'
    app:
        build:
            context: .
            dockerfile: Dockerfile
        #image: 'andresfuentes/checklist:{version}'
        image: 'andresfuentes/checklist'
        #hostname: $HOSTNAME
        environment:
            - 'SERVICE_ENV=prod,swagger'
            - 'SERVICE_PORT=9090'
            - 'SERVICE_DB=jdbc:postgresql://adc-database.eastus.cloudapp.azure.com:5432/Checklist'
            - 'DB_URL=adc-database.eastus.cloudapp.azure.com:5432/Checklist'
            - 'DB_USER=postgres'
            - 'DB_PASSWORD=pwc123'


            - 'SERVICE_ES_CLUSTER=elasticsearch'
            - 'SERVICE_ES_NODE=adc-database.eastus.cloudapp.azure.com:9300'
            - 'constraint:tier.app==true'
            - 'affinity:container!=~*app*'
        #network_mode: "service:checklist"
        ports:
            - '8080:9090'
        #restart: always



