version: '2'
services:

    cicd:
        extends:
           file: devops/cicd/docker-compose.yml
           service: cicd
        environment:
            - 'APP_NAME=checklist'
            - 'DEPLOY_TO_SERVER=dev'

            - 'DOCKER_USER=andresfuentes'


            - 'DOCKER_TARGET=tcp://adc-swarm-master.eastus.cloudapp.azure.com:4243'
            - 'GIT_URL=https://github.com/andresfuentes/Checklist.git'
            - 'HEALTH_CHECK=http://adc-swarm-master.eastus.cloudapp.azure.com:8080/management/health'

            - 'RFC_CREATE_IMPLEMENTATION_API_URL=http://adc-builder.eastus.cloudapp.azure.com:9993/api/rfc/changeImplementation'
            - 'RFC_EVALUATION_CLOSED_API_URL=http://adc-builder.eastus.cloudapp.azure.com:9993/api/rfc/closeWithEvaluation'


            - 'SERVICE_ENV=prod,swagger'
            - 'SERVICE_PORT=9090'
            - 'SERVICE_ES_CLUSTER=elasticsearch'
            - 'SERVICE_ES_NODE=adc-database.eastus.cloudapp.azure.com:9300'

            - 'SERVICE_DB=jdbc:postgresql://adc-database.eastus.cloudapp.azure.com:5432/Checklist'
            - 'DB_URL=adc-database.eastus.cloudapp.azure.com:5432/Checklist'
            - 'DB_USER=postgres'


            - 'DOCKER_PASSWORD=tresm1104'
            - 'DB_PASSWORD=pwc123'



    develop:
        extends:
           service: cicd
        environment:
            - 'DOCKER_TARGET=tcp://adc-swarm-master-dev.eastus.cloudapp.azure.com:4243'
        command: >
            bash -c '
            ./devops/cicd/deploy.sh
            '
    qa:
        extends:
           service: cicd
        environment:
            - 'DOCKER_TARGET=tcp://adc-swarm-master-qa.eastus.cloudapp.azure.com:4243'
        command: >
            bash -c '
            ./devops/cicd/deploy.sh
            '
    uat:
        extends:
           service: cicd
        environment:
            - 'DOCKER_TARGET=tcp://adc-swarm-master-uat.eastus.cloudapp.azure.com:4243'
        command: >
            bash -c '
            ./devops/cicd/deploy.sh
            '
    master:
        extends:
           service: cicd
        environment:
            - 'DOCKER_TARGET=tcp://adc-swarm-master.eastus.cloudapp.azure.com:4243'
        command: >
            bash -c '
            ./devops/cicd/deploy.sh
            '


    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: 'andresfuentes/checklist:{version}'
        #image: 'andresfuentes/checklist'
        #hostname: $HOSTNAME
        environment:
            - 'SERVICE_ENV=prod,swagger'
            - 'SERVICE_PORT=9090'
            - 'SERVICE_DB=jdbc:postgresql://adc-database.eastus.cloudapp.azure.com:5432/Checklist'
            - 'DB_URL=adc-database.eastus.cloudapp.azure.com:5432/Checklist'
            - 'DB_USER=postgres'
            - 'DB_PASSWORD=pwc123'


            - 'SERVICE_ES_CLUSTER=elasticsearch'
            - 'SERVICE_ES_NODE=adc-database.eastus.cloudapp.azure.com:9300'
            - 'constraint:tier.app==true'
            - 'affinity:container!=~*app*'
        ports:
            - '8080:9090'
        #restart: always


    local:
        extends:
           service: app
        image: 'andresfuentes/checklist:dev'
        # networks:
        #     - front
        #     - back


# volumes:
#   db-data:
#     driver: local


# networks:
#   front:
#     driver: overlay
#   back:
#     driver: overlay
#   default:
#     driver: overlay
