FROM ubuntu:xenial

MAINTAINER me@andresfuentes.com

##
## Install required dependencies
##
RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get -y install sudo apt-utils

#
# Create User
#
ENV APP_HOME /var/app
ARG user=jenkins
ARG group=jenkins
ARG uid=1000
ARG gid=1000


RUN \
    echo "%sudo ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
    groupadd -g ${gid} ${group} && \
    useradd -d "$APP_HOME" -u ${uid} -g ${gid} -G users,sudo -s /bin/bash -m ${user}

    #echo "secret\nsecret" | passwd ${user} && \

#
# Configure Docker client
#
RUN apt-get -y install curl sudo procps wget && \
    curl -fsSL https://experimental.docker.com/ | sh && \
    sudo apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


RUN usermod -aG docker ${user}
RUN gpasswd -a ${user} docker


#
# Install Docker Compose, Docker Machine in case we need them
#
RUN \
    curl --insecure -L https://github.com/docker/compose/releases/download/1.8.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose && \
    chmod +x /usr/local/bin/docker-compose


#
# Install Java and Exentials
#
RUN \
  apt-get update && \
  apt-get install -y git && \
  apt-get install -y nodejs && \
  ln -s `which nodejs` /usr/bin/node && \
  apt-get install -y npm && \
  apt-get install -y openjdk-8* && \
  apt-get install -y maven

#
# Install additional tools
#
RUN \
   npm install -g bower && \
   npm install -g gulp && \
   npm install -g yo && \
   npm install -g generator-jhipster

#
# Install Gradle
#
RUN \
   apt-get install -y gradle

#
# Install JQ
#
RUN apt-get install -y jq

#
# Install YAML2JSON and asciidoctor.jr to partes yaml files
#
RUN npm install -g yaml-to-json asciidoctor.js


#
# Give special permissions to ${user}
#
RUN \
   chmod -R 777 /var/cache && \
   chmod -R 777 /var/lib


#
# Work folder
#
RUN \
   mkdir -p /var/app && \
   mkdir -p /var/devops

COPY ./devops /var/devops

RUN \
   chmod -R +x /var/devops/*.sh && \
   chmod -R +x /var/devops/cicd/*.sh

WORKDIR /var/app

VOLUME ["/var/app/"]


#RUN chown -R ${user} $APP_HOME && \
#    chgrp -R ${user} $APP_HOME && \
#    chown -R ${user} /var/devops && \
#    chgrp -R ${user} /var/devops

#USER ${user}




#
# App Specific
#
#RUN cd /var/app
#RUN git clone https://github.com/andresfuentes/Checklist.git

#RUN \
#    echo "Installing Gulp" && \
#    cd /var/app/Checklist && \
#    gradle installGulp


ENTRYPOINT ["/var/devops/cli.sh"]
#CMD ["/var/devops/cli.sh"]


