FROM ubuntu:xenial

MAINTAINER me@andresfuentes.com

##
## Install required dependencies
##
RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get -y install sudo apt-utils


#RUN echo "builder ALL=NOPASSWD: ALL" >> /etc/sudoers

#
# Configure Docker client
#
RUN apt-get -y install curl sudo procps wget && \
    echo "%sudo ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
    useradd -u 1100 -G users,sudo -d /home/user --shell /bin/bash -m user && \
    echo "secret\nsecret" | passwd user && \
    curl -fsSL https://experimental.docker.com/ | sh && \
    usermod -aG docker user && sudo apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

    #&& \
    #usermod -aG docker builder

#
# Install Docker Compose, Docker Machine in case we need them
#
RUN \
    curl --insecure -L https://github.com/docker/compose/releases/download/1.6.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose && \
    chmod +x /usr/local/bin/docker-compose


#
# Install Java and Exentials
#
RUN \
  apt-get update && \
  apt-get install -y git && \
  apt-get install -y nodejs && \
  ln -s `which nodejs` /usr/bin/node && \
  apt-get install -y npm && \
  apt-get install -y openjdk-8* && \
  apt-get install -y maven

#
# Install additional tools
#
RUN \
   npm install -g bower && \
   npm install -g gulp && \
   npm install -g yo && \
   npm install -g generator-jhipster

#
# Install Gradle
#
RUN \
   apt-get install -y gradle


#
# Create User
#
ENV APP_HOME /var/app
ARG user=buildmaster
ARG group=buildmaster
ARG uid=1000
ARG gid=1000
RUN groupadd -g ${gid} ${group} \
    && useradd -d "$APP_HOME" -u ${uid} -g ${gid} -m -s /bin/bash ${user}

#
# Give special permissions to ${user}
#
RUN \
   chmod -R 777 /var/cache && \
   chmod -R 777 /var/lib

#Comment for now
USER ${user}
RUN chown -R ${user} "$APP_HOME"

#
# Work folder
#
#RUN mkdir -p /var/app
WORKDIR /var/app



RUN cd /var/app
RUN git clone https://github.com/andresfuentes/Checklist.git


RUN \
    echo "Installing Gulp" && \
    cd /var/app/Checklist && \
    gradle installGulp

VOLUME ["/var/app/Checklist"]


RUN chmod +x /var/app/Checklist/*.sh

CMD ["/var/app/Checklist/devops/cli.sh"]


