#!/bin/sh
echo "******************************************"
echo "* CICD CLI [$APP_NAME]                   *"
echo "* GIT URL  [$GIT_URL]                    *"
echo "*                                        *"
echo "* COMMANDs:                              *"
echo "*    - compile: Compile Code             *"
echo "*    - test:    Unit Testing             *"
echo "*    - scan:    Code Analisys            *"
echo "*    - package: Packaging App            *"
echo "*    - check:   Check App                *"
echo "*                                        *"
echo "-*****************************************"
