version: '2'
services:
    builder:
        build:
            context: jenkins
            dockerfile: Dockerfile-jenkins
        image: 'andresfuentes/builder'
        environment:
            - 'DEFAULT_USERNAME=pwc'
            - 'DEFAULT_PASSWORD={pwc-password}'
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "/var/jenkins_home/workspace:/var/jenkins_home/workspace"
        ports:
            - '8080:8080'
            - '50000:50000'
        restart: always

    sonarq:
        image: sonarqube
        environment:
            #- 'SONARQUBE_JDBC_USERNAME=admin'
            #- 'SONARQUBE_JDBC_PASSWORD=admin'
            - 'SONARQUBE_JDBC_USERNAME=pwc'
            - 'SONARQUBE_JDBC_PASSWORD={pwc-password}'
            - 'SONARQUBE_JDBC_URL=jdbc:postgresql://pirates-dtr.eastus.cloudapp.azure.com:5432/sonar'
        ports:
            - '9000:9000'
            - '9092:9092'


   database-postgresql:
        build:
            context: database
            dockerfile: Dockerfile-database
        #container_name: database
        image: 'andresfuentes/db'
        hostname: $HOSTNAME
        #domainname: pwcinternal.com
        #labels:
        #  - 'SERVICE_NAME=database'
        environment:
            #- 'VIRTUAL_HOST=iw2p2-database-dev.code348.com'
             - 'POSTGRES_PASSWORD={pwc-password}'
             - 'PGDATA=/data'
        volumes:
             - /var/data/postgresql:/data
        ports:
             - "5432:5432"
        restart: always

   database-mysql:
        image: 'mysql'
        hostname: $HOSTNAME
        #domainname: pwcinternal.com
        #labels:
        #  - 'SERVICE_NAME=database'
        environment:
            #- 'VIRTUAL_HOST=iw2p2-database-dev.code348.com'
             - 'MYSQL_PASSWORD={pwc-password}'
        volumes:
             - /var/data/mysql:/var/lib/mysql
        ports:
             - "3306:3306"
        restart: always

    search:
        image: 'elasticsearch:2.3.5'
        hostname: $HOSTNAME
        volumes:
             - /var/data/search:/usr/share/elastichsearch/data/
        ports:
             - "9200:9200"
             - '9300:9300'
        restart: always

    rfcautomation:
        # build: .
        # container_name: devops-rfcautomation-test
        image: 'andresfuentes/rfcautomation'
        hostname: $HOSTNAME
        domainname: eastus.cloudapp.azure.com
        # labels:
        #  - 'SERVICE_NAME=changeautomation-dmo'
        environment:
             #- 'VIRTUAL_HOST=changeautomation-dmo.pwcinternal.com'
             - 'constraint:tier.app==true'
             - 'affinity:container!=~*hub*'
             #- 'WSDL_ENDPOINT=http://pwcappv53.pwcinternal.com:14004/SM/7/ws'
             - 'WSDL_ENDPOINT=https://apimstg.pwc.com/SM/7/PwCChangeCSA.wsdl'
             - 'WSDL_ENDPOINT_WSDL=https://apimstg.pwc.com/SM/7/PwCChangeCSA.wsdl?wsdl'
             - 'WSDL_USERNAME=pwcdevopsuser'
             - 'WSDL_PASSWORD={hp9-password}'
             - 'LOG_LEVEL=debug'
             #- 'SWAGGER_HOST=changeautomation-dmo.pwcinternal.com'
             - 'PERSIST_DATA=true'
             - 'PG_SERVER=postgresqlserver'
             - 'PG_DB=changemgmtautomation'
             - 'PG_USER=pwc'
             - 'PG_PASSWORD={pwc-password}'
             - 'PG_PORT=5432'
             - 'API_KEY={api-key}'
             - 'API_KEY_SECRET={api-secret}'
        extra_hosts:
             - 'postgresqlserver:52.179.127.235'
        # links:
        #   - 'postgresqlserver:database'
        ports:
             - '9993:3000'
        restart: 'always'
