FROM jenkins:latest

USER root

MAINTAINER me@andresfuentes.com

##
## Install required dependencies
##
RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get -y install sudo apt-utils

#
# Configure Docker client
#
RUN apt-get -y install curl sudo procps wget && \
    echo "%sudo ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
    useradd -u 1100 -G users,sudo -d /home/user --shell /bin/bash -m user && \
    echo "secret\nsecret" | passwd user && \
    curl -fsSL https://experimental.docker.com/ | sh && \
    usermod -aG docker jenkins && sudo apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

    #&& \
    #usermod -aG docker builder

#
# Install Docker Compose, Docker Machine in case we need them
#
RUN \
    curl --insecure -L https://github.com/docker/compose/releases/download/1.6.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose && \
    chmod +x /usr/local/bin/docker-compose


##
## Create required folders
##
RUN mkdir /var/app && \
    mkdir /var/app/jobs && \
    mkdir /var/app/config && \
    mkdir /var/app/certs

#
# Copy RUN command
#
COPY  run.sh /run.sh
RUN chmod +x /run.sh
ENTRYPOINT ["/bin/tini", "--", "/run.sh"]

##
## Update Jenkins
##

# This cannot be copied directly to jenkins_home b/c is a VOLUME
COPY jenkins/jobs/ /var/app/jobs/
COPY jenkins/config/ /var/app/config/

# Update Plugins
COPY plugins.txt /plugins.txt
RUN /usr/local/bin/plugins.sh /plugins.txt


USER jenkins


