FROM ubuntu:xenial

MAINTAINER me@andresfuentes.com

##
## Install required dependencies
##
RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get -y install sudo apt-utils

#
# Install Java and Exentials
#
RUN \
  apt-get update && \
  apt-get install -y openjdk-8*


#
# Install required modules
#
RUN apt-get -y install curl sudo procps wget


RUN mkdir -p /var/app
WORKDIR /var/app

#
# Install Slave Jar
#
RUN \
   wget http://pirates-builder.eastus.cloudapp.azure.com:8080/jnlpJars/slave.jar -O /var/app/slave.jar

RUN apt-get install -y openssh-server
RUN mkdir /var/run/sshd
RUN echo 'root:pwc' | chpasswd
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
